plugins:
  webhook_digest_enabled:
    default: false
  webhook_digest_shared_secret:
    default: ''
  webhook_digest_url:
    default: ''  
  webhook_digest_interval_hours:
    default: 72
  webhook_digest_types:
    default: json+html
    type: enum
    choices:
    - json
    - html
    - json+html
